package org.novadeck.jxla.tools;

import java.util.*;
/**
 *
 * @author  nioto
 */
public class Bots
{
    final static String m_bots[] = (String[])getBots ().toArray ( new String[0]) ;
    final static Map<String,String> m_botNames = getBotNames ();
    
    
    public static String getBot(String ua)
    {
        String tmp = ua.toLowerCase ();
        for (int i=0; i< m_bots.length; i++)
        {
            if ( tmp.indexOf ( m_bots[i] ) >=0)
            {
                return m_bots[i];
            }
        }
        return null;
    }
    
    public static String getBotName( String bot )
    {
        return m_botNames.get ( bot ); 
    }
    
    private static List<String> getBots ()
    {
        List<String> list = new ArrayList<String> ();
        list.add ( "antibot");
        list.add ( "appie");
        list.add ( "architext");
        list.add ( "bjaaland");
        list.add ( "digout4u");
        list.add ( "echo");
        list.add ( "fast-webcrawler");
        list.add ( "ferret");
        list.add ( "googlebot");
        list.add ( "gulliver");
        list.add ( "harvest");
        list.add ( "htdig");
        list.add ( "ia_archiver");
        list.add ( "jeeves");
        list.add ( "jennybot");
        list.add ( "linkwalker");
        list.add ( "lycos");
        list.add ( "mercator");
        list.add ( "moget");
        list.add ( "muscatferret");
        list.add ( "myweb");
        list.add ( "netcraft");
        list.add ( "nomad");
        list.add ( "petersnews");
        list.add ( "scooter");
        list.add ( "slurp");
        list.add ( "unlost_web_crawler");
        list.add ( "voila");
        list.add ( "voyager");
        list.add ( "webbase");
        list.add ( "weblayers");
        list.add ( "wget");
        list.add ( "wisenutbot");
        list.add ( "acme.spider");
        list.add ( "ahoythehomepagefinder");
        list.add ( "alkaline");
        list.add ( "arachnophilia");
        list.add ( "aretha");
        list.add ( "ariadne");
        list.add ( "arks");
        list.add ( "aspider");
        list.add ( "atn.txt");
        list.add ( "atomz");
        list.add ( "auresys");
        list.add ( "backrub");
        list.add ( "bigbrother");
        list.add ( "blackwidow");
        list.add ( "blindekuh");
        list.add ( "bloodhound");
        list.add ( "brightnet");
        list.add ( "bspider");
        list.add ( "cactvschemistryspider");
        list.add ( "cassandra");
        list.add ( "cgireader");
        list.add ( "checkbot");
        list.add ( "churl");
        list.add ( "cmc");
        list.add ( "collective");
        list.add ( "combine");
        list.add ( "conceptbot");
        list.add ( "coolbot");
        list.add ( "core");
        list.add ( "cosmos");
        list.add ( "cruiser");
        list.add ( "cusco");
        list.add ( "cyberspyder");
        list.add ( "deweb");
        list.add ( "dienstspider");
        list.add ( "digger");
        list.add ( "diibot");
        list.add ( "directhit");
        list.add ( "dnabot");
        list.add ( "download_express");
        list.add ( "dragonbot");
        list.add ( "dwcp");
        list.add ( "e-collector");
        list.add ( "ebiness");
        list.add ( "eit");
        list.add ( "elfinbot");
        list.add ( "emacs");
        list.add ( "emcspider");
        list.add ( "esther");
        list.add ( "evliyacelebi");
        list.add ( "nzexplorer");
        list.add ( "fdse");
        list.add ( "felix");
        list.add ( "fetchrover");
        list.add ( "fido");
        list.add ( "finnish");
        list.add ( "fireball");
        list.add ( "fouineur");
        list.add ( "francoroute");
        list.add ( "freecrawl");
        list.add ( "funnelweb");
        list.add ( "gama");
        list.add ( "gazz");
        list.add ( "gcreep");
        list.add ( "getbot");
        list.add ( "geturl");
        list.add ( "golem");
        list.add ( "grapnel");
        list.add ( "griffon");
        list.add ( "gromit");
        list.add ( "hambot");
        list.add ( "havindex");
        list.add ( "hometown");
        list.add ( "htmlgobble");
        list.add ( "hyperdecontextualizer");
        list.add ( "iajabot");
        list.add ( "ibm");
        list.add ( "iconoclast");
        list.add ( "ilse");
        list.add ( "imagelock");
        list.add ( "incywincy");
        list.add ( "informant");
        list.add ( "infoseek");
        list.add ( "infoseeksidewinder");
        list.add ( "infospider");
        list.add ( "inspectorwww");
        list.add ( "intelliagent");
        list.add ( "irobot");
        list.add ( "iron33");
        list.add ( "israelisearch");
        list.add ( "javabee");
        list.add ( "jbot");
        list.add ( "jcrawler");
        list.add ( "jobo");
        list.add ( "jobot");
        list.add ( "joebot");
        list.add ( "jubii");
        list.add ( "jumpstation");
        list.add ( "katipo");
        list.add ( "kdd");
        list.add ( "kilroy");
        list.add ( "ko_yappo_robot");
        list.add ( "labelgrabber.txt");
        list.add ( "larbin");
        list.add ( "legs");
        list.add ( "linkidator");
        list.add ( "linkscan");
        list.add ( "lockon");
        list.add ( "logo_gif");
        list.add ( "macworm");
        list.add ( "magpie");
        list.add ( "marvin");
        list.add ( "mattie");
        list.add ( "mediafox");
        list.add ( "merzscope");
        list.add ( "meshexplorer");
        list.add ( "mindcrawler");
        list.add ( "momspider");
        list.add ( "monster");
        list.add ( "motor");
        list.add ( "mwdsearch");
        list.add ( "netcarta");
        list.add ( "netmechanic");
        list.add ( "netscoop");
        list.add ( "newscan-online");
        list.add ( "nhse");
        list.add ( "northstar");
        list.add ( "occam");
        list.add ( "octopus");
        list.add ( "openfind");
        list.add ( "orb_search");
        list.add ( "packrat");
        list.add ( "pageboy");
        list.add ( "parasite");
        list.add ( "patric");
        list.add ( "pegasus");
        list.add ( "perignator");
        list.add ( "perlcrawler");
        list.add ( "phantom");
        list.add ( "piltdownman");
        list.add ( "pimptrain");
        list.add ( "pioneer");
        list.add ( "pitkow");
        list.add ( "pjspider");
        list.add ( "pka");
        list.add ( "plumtreewebaccessor");
        list.add ( "poppi");
        list.add ( "portalb");
        list.add ( "puu");
        list.add ( "python");
        list.add ( "raven");
        list.add ( "rbse");
        list.add ( "resumerobot");
        list.add ( "rhcs");
        list.add ( "roadrunner");
        list.add ( "robbie");
        list.add ( "robi");
        list.add ( "robofox");
        list.add ( "robozilla");
        list.add ( "roverbot");
        list.add ( "rules");
        list.add ( "safetynetrobot");
        list.add ( "search_au");
        list.add ( "searchprocess");
        list.add ( "senrigan");
        list.add ( "sgscout");
        list.add ( "shaggy");
        list.add ( "shaihulud");
        list.add ( "sift");
        list.add ( "simbot");
        list.add ( "site-valet");
        list.add ( "sitegrabber");
        list.add ( "sitetech");
        list.add ( "slcrawler");
        list.add ( "smartspider");
        list.add ( "snooper");
        list.add ( "solbot");
        list.add ( "spanner");
        list.add ( "speedy");
        list.add ( "spider_monkey");
        list.add ( "spiderbot");
        list.add ( "spiderline");
        list.add ( "spiderman");
        list.add ( "spiderview");
        list.add ( "spry");
        list.add ( "ssearcher");
        list.add ( "suke");
        list.add ( "suntek");
        list.add ( "sven");
        list.add ( "tach_bw");
        list.add ( "tarantula");
        list.add ( "tarspider");
        list.add ( "techbot");
        list.add ( "templeton");
        list.add ( "teoma_agent1");
        list.add ( "titin");
        list.add ( "titan");
        list.add ( "tkwww");
        list.add ( "tlspider");
        list.add ( "ucsd");
        list.add ( "udmsearch");
        list.add ( "urlck");
        list.add ( "valkyrie");
        list.add ( "victoria");
        list.add ( "visionsearch");
        list.add ( "vwbot");
        list.add ( "w3index");
        list.add ( "w3m2");
        list.add ( "wallpaper");
        list.add ( "wanderer");
        list.add ( "wapspider");
        list.add ( "webbandit");
        list.add ( "webcatcher");
        list.add ( "webcopy");
        list.add ( "webfetcher");
        list.add ( "webfoot");
        list.add ( "weblinker");
        list.add ( "webmirror");
        list.add ( "webmoose");
        list.add ( "webquest");
        list.add ( "webreader");
        list.add ( "webreaper");
        list.add ( "websnarf");
        list.add ( "webspider");
        list.add ( "webvac");
        list.add ( "webwalk");
        list.add ( "webwalker");
        list.add ( "webwatch");
        list.add ( "whatuseek");
        list.add ( "whowhere");
        list.add ( "wired-digital");
        list.add ( "wmir");
        list.add ( "wolp");
        list.add ( "wombat");
        list.add ( "worm");
        list.add ( "wwwc");
        list.add ( "wz101");
        list.add ( "xget");
        list.add ( "awbot");
        list.add ( "baiduspider");
        list.add ( "bobby");
        list.add ( "boris");
        list.add ( "bumblebee");
        list.add ( "cscrawler");
        list.add ( "daviesbot");
        list.add ( "exactseek");
        list.add ( "ezresult");
        list.add ( "gigabot");
        list.add ( "gnodspider");
        list.add ( "internetseer");
        list.add ( "justview");
        list.add ( "linkbot");
        list.add ( "linkchecker");
        list.add ( "msiecrawler");
        list.add ( "nederland.zoek");
        list.add ( "perman");
        list.add ( "pompos");
        list.add ( "psbot");
        list.add ( "redalert");
        list.add ( "shoutcast");
        list.add ( "slysearch");
        list.add ( "surveybot");
        list.add ( "turnitinbot");
        list.add ( "ultraseek");
        list.add ( "webclipping.com");
        list.add ( "webcompass");
        list.add ( "yandex");
        list.add ( "zealbot");
        list.add ( "zyborg");
        list.add ( "robot");
        list.add ( "crawl");
        list.add ( "spider");
        return list;
    }
    
    private static Map<String,String> getBotNames ()
    {
        Map<String,String> map = new HashMap<String,String> ();
        map.put ("acme.spider", "Acme.Spider");
        map.put ("ahoythehomepagefinder", "Ahoy! The Homepage Finder");
        map.put ("alkaline", "Alkaline");
        map.put ("antibot", "Antibot");
        map.put ("appie", "Walhello appie");
        map.put ("arachnophilia", "Arachnophilia");
        map.put ("architext", "ArchitextSpider");
        map.put ("aretha", "Aretha");
        map.put ("ariadne", "ARIADNE");
        map.put ("arks", "arks");
        map.put ("aspider", "ASpider (Associative Spider);");
        map.put ("atn.txt", "ATN Worldwide");
        map.put ("atomz", "Atomz.com Search Robot");
        map.put ("auresys", "AURESYS");
        map.put ("awbot", "AWBot");
        map.put ("backrub", "BackRub");
        map.put ("baiduspider", "BaiDuSpider");
        map.put ("bigbrother", "Big Brother");
        map.put ("bjaaland", "Bjaaland");
        map.put ("blackwidow", "BlackWidow");
        map.put ("blindekuh", "Die Blinde Kuh");
        map.put ("bloodhound", "Bloodhound");
        map.put ("bobby", "Bobby");
        map.put ("boris", "Boris");
        map.put ("brightnet", "bright.net caching robot");
        map.put ("bspider", "BSpider");
        map.put ("bumblebee", "Bumblebee (relevare.com);");
        map.put ("cactvschemistryspider", "CACTVS Chemistry Spider");
        map.put ("cassandra", "Cassandra");
        map.put ("cgireader", "Digimarc Marcspider/CGI");
        map.put ("checkbot", "Checkbot");
        map.put ("churl", "churl");
        map.put ("cmc", "CMC/0.01");
        map.put ("collective", "Collective");
        map.put ("combine", "Combine System");
        map.put ("conceptbot", "Conceptbot");
        map.put ("coolbot", "CoolBot");
        map.put ("core", "Web Core / Roots");
        map.put ("cosmos", "XYLEME Robot");
        map.put ("crawl", "Unknown robot (identified by 'crawl');");
        map.put ("cruiser", "Internet Cruiser Robot");
        map.put ("cscrawler", "CsCrawler");
        map.put ("cusco", "Cusco");
        map.put ("cyberspyder", "CyberSpyder Link Test");
        map.put ("daviesbot", "DaviesBot");
        map.put ("deweb", "DeWeb(c); Katalog/Index");
        map.put ("dienstspider", "DienstSpider");
        map.put ("digger", "Digger");
        map.put ("digout4u", "Digout4u");
        map.put ("diibot", "Digital Integrity Robot");
        map.put ("directhit", "Direct Hit Grabber");
        map.put ("dnabot", "DNAbot");
        map.put ("download_express", "DownLoad Express");
        map.put ("dragonbot", "DragonBot");
        map.put ("dwcp", "DWCP (Dridus' Web Cataloging Project);");
        map.put ("e-collector", "e-collector");
        map.put ("ebiness", "EbiNess");
        map.put ("echo", "EchO!");
        map.put ("eit", "EIT Link Verifier Robot");
        map.put ("elfinbot", "ELFINBOT");
        map.put ("emacs", "Emacs-w3 Search Engine");
        map.put ("emcspider", "ananzi");
        map.put ("esther", "Esther");
        map.put ("evliyacelebi", "Evliya Celebi");
        map.put ("exactseek", "ExactSeek Crawler");
        map.put ("ezresult", "Ezresult");
        map.put ("fast-webcrawler", "Fast-Webcrawler (AllTheWeb);");
        map.put ("fdse", "Fluid Dynamics Search Engine robot");
        map.put ("felix", "Felix IDE");
        map.put ("ferret", "Wild Ferret Web Hopper #1, #2, #3");
        map.put ("fetchrover", "FetchRover");
        map.put ("fido", "fido");
        map.put ("finnish", "H�m�h�kki");
        map.put ("fireball", "KIT-Fireball");
        map.put ("fouineur", "Fouineur");
        map.put ("francoroute", "Robot Francoroute");
        map.put ("freecrawl", "Freecrawl");
        map.put ("funnelweb", "FunnelWeb");
        map.put ("gama", "gammaSpider, FocusedCrawler");
        map.put ("gazz", "gazz");
        map.put ("gcreep", "GCreep");
        map.put ("getbot", "GetBot");
        map.put ("geturl", "GetURL");
        map.put ("gigabot", "GigaBot");
        map.put ("gnodspider", "GNOD Spider");
        map.put ("golem", "Golem");
        map.put ("googlebot", "Googlebot (Google);");
        map.put ("grapnel", "Grapnel/0.01 Experiment");
        map.put ("griffon", "Griffon");
        map.put ("gromit", "Gromit");
        map.put ("gulliver", "Northern Light Gulliver");
        map.put ("hambot", "HamBot");
        map.put ("harvest", "Harvest");
        map.put ("havindex", "havIndex");
        map.put ("hometown", "Hometown Spider Pro");
        map.put ("htdig", "ht://Dig");
        map.put ("htmlgobble", "HTMLgobble");
        map.put ("hyperdecontextualizer", "Hyper-Decontextualizer");
        map.put ("ia_archiver", "Alexa (IA Archiver);");
        map.put ("iajabot", "iajaBot");
        map.put ("ibm", "IBM_Planetwide");
        map.put ("iconoclast", "Popular Iconoclast");
        map.put ("ilse", "Ingrid");
        map.put ("imagelock", "Imagelock");
        map.put ("incywincy", "IncyWincy");
        map.put ("informant", "Informant");
        map.put ("infoseek", "InfoSeek Robot 1.0");
        map.put ("infoseeksidewinder", "Infoseek Sidewinder");
        map.put ("infospider", "InfoSpiders");
        map.put ("inspectorwww", "Inspector Web");
        map.put ("intelliagent", "IntelliAgent");
        map.put ("internetseer", "InternetSeer");
        map.put ("irobot", "I, Robot");
        map.put ("iron33", "Iron33");
        map.put ("israelisearch", "Israeli-search");
        map.put ("javabee", "JavaBee");
        map.put ("jbot", "JBot Java Web Robot");
        map.put ("jcrawler", "JCrawler");
        map.put ("jeeves", "Jeeves");
        map.put ("jennybot", "JennyBot");
        map.put ("jobo", "JoBo Java Web Robot");
        map.put ("jobot", "Jobot");
        map.put ("joebot", "JoeBot");
        map.put ("jubii", "The Jubii Indexing Robot");
        map.put ("jumpstation", "JumpStation");
        map.put ("justview", "JustView");
        map.put ("katipo", "Katipo");
        map.put ("kdd", "KDD-Explorer");
        map.put ("kilroy", "Kilroy");
        map.put ("ko_yappo_robot", "KO_Yappo_Robot");
        map.put ("labelgrabber.txt", "LabelGrabber");
        map.put ("larbin", "larbin");
        map.put ("legs", "legs");
        map.put ("linkbot", "LinkBot");
        map.put ("linkchecker", "LinkChecker");
        map.put ("linkidator", "Link Validator");
        map.put ("linkscan", "LinkScan");
        map.put ("linkwalker", "LinkWalker");
        map.put ("lockon", "Lockon");
        map.put ("logo_gif", "logo.gif Crawler");
        map.put ("lycos", "Lycos");
        map.put ("macworm", "Mac WWWWorm");
        map.put ("magpie", "Magpie");
        map.put ("marvin", "marvin/infoseek");
        map.put ("mattie", "Mattie");
        map.put ("mediafox", "MediaFox");
        map.put ("mercator", "Mercator");
        map.put ("merzscope", "MerzScope");
        map.put ("meshexplorer", "NEC-MeshExplorer");
        map.put ("mindcrawler", "MindCrawler");
        map.put ("moget", "moget");
        map.put ("momspider", "MOMspider");
        map.put ("monster", "Monster");
        map.put ("motor", "Motor");
        map.put ("msiecrawler", "MSIECrawler");
        map.put ("muscatferret", "Muscat Ferret");
        map.put ("mwdsearch", "Mwd.Search");
        map.put ("myweb", "Internet Shinchakubin");
        map.put ("nederland.zoek", "Nederland.zoek");
        map.put ("netcarta", "NetCarta WebMap Engine");
        map.put ("netcraft", "Netcraft Web Server Survey");
        map.put ("netmechanic", "NetMechanic");
        map.put ("netscoop", "NetScoop");
        map.put ("newscan-online", "newscan-online");
        map.put ("nhse", "NHSE Web Forager");
        map.put ("nomad", "Nomad");
        map.put ("northstar", "The NorthStar Robot");
        map.put ("nzexplorer", "nzexplorer");
        map.put ("occam", "Occam");
        map.put ("octopus", "HKU WWW Octopus");
        map.put ("openfind", "Openfind data gatherer");
        map.put ("orb_search", "Orb Search");
        map.put ("packrat", "Pack Rat");
        map.put ("pageboy", "PageBoy");
        map.put ("parasite", "ParaSite");
        map.put ("patric", "Patric");
        map.put ("pegasus", "pegasus");
        map.put ("perignator", "The Peregrinator");
        map.put ("perlcrawler", "PerlCrawler 1.0");
        map.put ("perman", "Perman surfer");
        map.put ("petersnews", "Petersnews");
        map.put ("phantom", "Phantom");
        map.put ("piltdownman", "PiltdownMan");
        map.put ("pimptrain", "Pimptrain.com's robot");
        map.put ("pioneer", "Pioneer");
        map.put ("pitkow", "html_analyzer");
        map.put ("pjspider", "Portal Juice Spider");
        map.put ("pka", "PGP Key Agent");
        map.put ("plumtreewebaccessor", "PlumtreeWebAccessor");
        map.put ("pompos", "Pompos");
        map.put ("poppi", "Poppi");
        map.put ("portalb", "PortalB Spider");
        map.put ("psbot", "psBot");
        map.put ("puu", "GetterroboPlus Puu");
        map.put ("python", "The Python Robot");
        map.put ("raven", "Raven Search");
        map.put ("rbse", "RBSE Spider");
        map.put ("redalert", "Red Alert");
        map.put ("resumerobot", "Resume Robot");
        map.put ("rhcs", "RoadHouse Crawling System");
        map.put ("roadrunner", "Road Runner: The ImageScape Robot");
        map.put ("robbie", "Robbie the Robot");
        map.put ("robi", "ComputingSite Robi/1.0");
        map.put ("robofox", "RoboFox");
        map.put ("robot", "Unknown robot (identified by 'robot');");
        map.put ("robozilla", "Robozilla");
        map.put ("roverbot", "Roverbot");
        map.put ("rules", "RuLeS");
        map.put ("safetynetrobot", "SafetyNet Robot");
        map.put ("scooter", "Scooter (AltaVista);");
        map.put ("search_au", "Search.Aus-AU.COM");
        map.put ("searchprocess", "SearchProcess");
        map.put ("senrigan", "Senrigan");
        map.put ("sgscout", "SG-Scout");
        map.put ("shaggy", "ShagSeeker");
        map.put ("shaihulud", "Shai'Hulud");
        map.put ("shoutcast", "Shoutcast Directory Service");
        map.put ("sift", "Sift");
        map.put ("simbot", "Simmany Robot Ver1.0");
        map.put ("site-valet", "Site Valet");
        map.put ("sitegrabber", "Open Text Index Robot");
        map.put ("sitetech", "SiteTech-Rover");
        map.put ("slcrawler", "SLCrawler");
        map.put ("slurp", "Inktomi Slurp");
        map.put ("slysearch", "SlySearch");
        map.put ("smartspider", "Smart Spider");
        map.put ("snooper", "Snooper");
        map.put ("solbot", "Solbot");
        map.put ("spanner", "Spanner");
        map.put ("speedy", "Speedy Spider");
        map.put ("spider", "Unknown robot (identified by 'spider');");
        map.put ("spider_monkey", "spider_monkey");
        map.put ("spiderbot", "SpiderBot");
        map.put ("spiderline", "Spiderline Crawler");
        map.put ("spiderman", "SpiderMan");
        map.put ("spiderview", "SpiderView(tm);");
        map.put ("spry", "Spry Wizard Robot");
        map.put ("ssearcher", "Site Searcher");
        map.put ("suke", "Suke");
        map.put ("suntek", "suntek search engine");
        map.put ("surveybot", "SurveyBot");
        map.put ("sven", "Sven");
        map.put ("tach_bw", "TACH Black Widow");
        map.put ("tarantula", "Tarantula");
        map.put ("tarspider", "tarspider");
        map.put ("techbot", "TechBOT");
        map.put ("templeton", "Templeton");
        map.put ("teoma_agent1", "TeomaTechnologies");
        map.put ("titan", "TITAN");
        map.put ("titin", "TitIn");
        map.put ("tkwww", "The TkWWW Robot");
        map.put ("tlspider", "TLSpider");
        map.put ("turnitinbot", "Turn It In");
        map.put ("ucsd", "UCSD Crawl");
        map.put ("udmsearch", "UdmSearch");
        map.put ("ultraseek", "Ultraseek");
        map.put ("unlost_web_crawler", "Unlost Web Crawler");
        map.put ("urlck", "URL Check");
        map.put ("valkyrie", "Valkyrie");
        map.put ("victoria", "Victoria");
        map.put ("visionsearch", "vision-search");
        map.put ("voila", "Voila");
        map.put ("voyager", "Voyager");
        map.put ("vwbot", "VWbot");
        map.put ("w3index", "The NWI Robot");
        map.put ("w3m2", "W3M2");
        map.put ("wallpaper", "WallPaper");
        map.put ("wanderer", "the World Wide Web Wanderer");
        map.put ("wapspider", "w@pSpider by wap4.com");
        map.put ("webbandit", "WebBandit Web Spider");
        map.put ("webbase", "WebBase");
        map.put ("webcatcher", "WebCatcher");
        map.put ("webclipping.com", "WebClipping.com");
        map.put ("webcompass", "webcompass");
        map.put ("webcopy", "WebCopy");
        map.put ("webfetcher", "Webfetcher");
        map.put ("webfoot", "The Webfoot Robot");
        map.put ("weblayers", "Weblayers");
        map.put ("weblinker", "WebLinker");
        map.put ("webmirror", "WebMirror");
        map.put ("webmoose", "The Web Moose");
        map.put ("webquest", "WebQuest");
        map.put ("webreader", "Digimarc MarcSpider");
        map.put ("webreaper", "WebReaper");
        map.put ("websnarf", "Websnarf");
        map.put ("webspider", "WebSpider");
        map.put ("webvac", "WebVac");
        map.put ("webwalk", "webwalk");
        map.put ("webwalker", "WebWalker");
        map.put ("webwatch", "WebWatch");
        map.put ("wget", "Wget");
        map.put ("whatuseek", "whatUseek Winona");
        map.put ("whowhere", "WhoWhere Robot");
        map.put ("wired-digital", "Wired Digital");
        map.put ("wisenutbot", "WISENutbot (Looksmart);");
        map.put ("wmir", "w3mir");
        map.put ("wolp", "WebStolperer");
        map.put ("wombat", "The Web Wombat");
        map.put ("worm", "The World Wide Web Worm");
        map.put ("wwwc", "WWWC Ver 0.2.5");
        map.put ("wz101", "WebZinger");
        map.put ("xget", "XGET");
        map.put ("yandex", "Yandex bot");
        map.put ("zealbot", "ZealBot");
        map.put ("zyborg", "Zyborg (Looksmart);");
        return map;
    }
    
}
